# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@influxdata/influxdb-client-1.18.0" = {
      name = "_at_influxdata_slash_influxdb-client";
      packageName = "@influxdata/influxdb-client";
      version = "1.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@influxdata/influxdb-client/-/influxdb-client-1.18.0.tgz";
        sha512 = "0C2mKb5hR61WqiWzwEwqHvBkYzaFI4QLKaffGj3IPHoouKYoFQSCLHK5C3Jws25LopqWvellVimf12CsnZXzGg==";
      };
    };
    "axios-0.21.4" = {
      name = "axios";
      packageName = "axios";
      version = "0.21.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.21.4.tgz";
        sha512 = "ut5vewkiu8jjGBdqpM44XxjuCjq9LAKeHVmoVfHVzy8eHgxxq8SbAVQNovDA8mVi05kP0Ea/n/UzcSHcTJQfNg==";
      };
    };
    "dotenv-10.0.0" = {
      name = "dotenv";
      packageName = "dotenv";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dotenv/-/dotenv-10.0.0.tgz";
        sha512 = "rlBi9d8jpv9Sf1klPjNfFAuWDjKLwTIJJ/VxtoTwIR6hnZxcEOQCZg2oIL3MWBYw5GpUDKOEnND7LXTbIpQ03Q==";
      };
    };
    "follow-redirects-1.14.4" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.14.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.14.4.tgz";
        sha512 = "zwGkiSXC1MUJG/qmeIFH2HBJx9u0V46QGUe3YR1fXG8bXQxq7fLj0RjLZQ5nubr9qNJUZrH+xUcwXEoXNpfS+g==";
      };
    };
    "influx-5.9.2" = {
      name = "influx";
      packageName = "influx";
      version = "5.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/influx/-/influx-5.9.2.tgz";
        sha512 = "N2YRIQiwCO60BzmzEzTxyWj/hDNsce2CLSmki8S1qbRwwuKecfvC6n0OwJrFV70lk5CpU/sLsOZFIy6PP01nOA==";
      };
    };
  };
  args = {
    name = "octopus-exporter";
    packageName = "octopus-exporter";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@influxdata/influxdb-client-1.18.0"
      sources."axios-0.21.4"
      sources."dotenv-10.0.0"
      sources."follow-redirects-1.14.4"
      sources."influx-5.9.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
